name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: build & test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: go build
        run: go build ./...

      - name: go test
        run: go test -v ./...
